version: '3'
services:
  vprodb:
    image: vikaszalavadiya/v-db:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/msql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: vikaszalavadiya/v-app:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: vikaszalavadiya/v-web:V1
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
